### ISSUE TITLE
请教大佬几个问题。

### ISSUE THREAD

**Issue by do-one-thing-to-well** [WinWang/ApplicationInit#1]
大佬，你好，我最近在做模块化开发的时候，想对子Module的初始化进行统一管理，思路是通过APT+JavaPoet统一生成对应的各个模块的初始化代码，这样主Module Application#onCreate中只用调用一句初始化代码可以完成所有子Module的初始化代码块调用，，，但是经过测试发现，，APT只能扫描当前被依赖的Module，子Module里代码是不扫描的，，，我有试过让每个子Module都依赖APT模块，但是发现APT会在每个Module build时单独编译执行，，，我在Github上找到了你的这个项目，，，看了你的实现思路，，有几个问题不明白，特此请教：
1.你的思路是通过自定义Plugin扫描然后用ASM插桩方式实现子Module的初始化么？（很抱歉，对自定义Plugin和ASM插桩不熟悉）
2.如果条件1成立的话，为什么还要单独写了一个ApplicationProcessor类处理注解呢，，，
麻烦了，，

**Comment by WinWang** [comment]
1、Processcor的目的是处理项目注解标识的类，真对被注解标识的类生成一系列代码，类似ButterKnife这种库，生成需要的代码
![image](https://user-images.githubusercontent.com/19348069/191728135-d4c15713-749b-46d6-8e60-211aac99fe4a.png)
2、Plugin的主要目的是真对现有的代码去做动态修改，比如你有一个类，有onCreate方法，我需要在这个类的onCreate方法里面加入一行代码，这时候就需要借助ASM对代码织入修改
大致的思路是这样

**Comment by do-one-thing-to-well** [comment]
感谢，看懂了。晚上查了好大一会儿，发现我的问题无法单独通过APT解决，
作为感谢，请允许我在这儿分享一下我遇到的问题及查询结果：
**先说我的期望：**
 主Module App有两个Library依赖，分别命名为Module1和Module2，在lib_annotation中定义了一个AppInit注解，，在lib_compiler中有一个AppInitProcessor继承于AbstractProcessor，，我希望的是使用APT技术能在构建期间获取到所有Module下的AppInit类注解信息，但是只能获取到顶层App Module里面的AppInit注解信息，其他子Module获取不到。
**查询结果：**
在StackOverFlow上遇到一个高度相似的问题，[参考](https://stackoverflow.com/questions/38492208/multi-module-annotation-processing-in-android-studio) 根据回答中的“may be considered as a proof that it's impossible to implement desired cross-module annotation processor.”来看，似乎这个期望因为跨模块无法单纯用APT实现。

希望这个对你有帮助，再次感谢。

**Comment by WinWang** [comment]
我没太明白你的意思，注解扫描的应该是整个项目层面的，不区分Module的
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/19348069/191779332-993a9384-d45d-48bd-b49a-20c085b095af.png">

**Comment by do-one-thing-to-well** [comment]
是这样的，以你上面的图中红框为例，此时获取到的Set<Element>是区分Module的，也就是App Module里整个AbstractProcessor会执行init->process，，子Module中也会执行init->process 这些方法流程，，而我一开始的以为是，整个App项目，添加一个AbstractProcessor，只用执行一次init方法，，然后可能会执行多次process方法，这样，我就可以使用APT扫描得到整个App项目中使用到我自己定义的注解类信息，，但是经过测试发现，是区分Module的，我所说的区分Module是这个意思，，，
我只是想在我做的模块化Android项目中，使用APT+JavaPoet动态生成各个子模块的初始化调用代码，将这些子模块的初始化代码动态生成放在一个类里面而已，这样不是更加灵活嘛，，，，我不知道我这么说有没有说明白，，

**Comment by do-one-thing-to-well** [comment]
昨晚看了StackOverFlow上的解释，我后来想明白了，，本来APT跟Gradle的构建有关系，如Builder out 窗口中的输出:
**>Task :app:kaptDebugKotlin**
这里的app是Module名称，，执行到这里，APT开始扫描相应的AppModule下的注解信息，，如果是其他子Module，需要执行：
**>Task :${moduel_name}:kaptDebugKotlin**   （这里module_name）表示任意Module的名称
执行各自模块下的APT扫描，，

事实上，还是我自己存在误解，功力不够，以为只要定义一个AbstractProcessor就可以一次性扫描获取到整个App项目（n个子Module）中相应的注解信息，，事实上，是我理解有误，

**Comment by WinWang** [comment]
> 是这样的，以你上面的图中红框为例，此时获取到的Set是区分Module的，也就是App Module里整个AbstractProcessor会执行init->process，，子Module中也会执行init->process 这些方法流程，，而我一开始的以为是，整个App项目，添加一个AbstractProcessor，只用执行一次init方法，，然后可能会执行多次process方法，这样，我就可以使用APT扫描得到整个App项目中使用到我自己定义的注解类信息，，但是经过测试发现，是区分Module的，我所说的区分Module是这个意思，，， 我只是想在我做的模块化Android项目中，使用APT+JavaPoet动态生成各个子模块的初始化调用代码，将这些子模块的初始化代码动态生成放在一个类里面而已，这样不是更加灵活嘛，，，，我不知道我这么说有没有说明白，，

我大概知道你的意思，这个是不行的，必须在每个模块依赖对应的Processor才行，你可以看下Arouter等框架都是一样的，因为字模块不依赖对应的api和processor的话，其实你也没办法引用到对应的注解API

**Comment by do-one-thing-to-well** [comment]
耽误你时间了，，，正在加急补充知识，，，因为看你的代码自定义Plugin和插桩那儿还是盲区，，再次感谢大佬提供的解决思路，感谢。

**Comment by do-one-thing-to-well** [comment]
今天试了一下你README里提供的依赖方式，发现报错，一开始是"Plugin with id 'com.winwang.plugin.lifecycle' not found."
然后我在classPath里添加 classpath 'com.winwang.plugin.lifecycle:applifecycle-plugin:1.3.0' 一样不行，Maven和Jitpack几个仓库都报404，是我引入方式不对么？

**Comment by do-one-thing-to-well** [comment]
又排查了一下问题，发现两处错误，第一最新版本是1.0.3，第二版本名前有一个v
解决了。
